[[task_rules]]

= Do One Task

_Start title with verb form such as Create or Creating._

_A task topic is a procedure written with numbered steps -- what a customer needs to do to accomplish a goal successfully._

This paragraph explains why the user performs the task or sets the context of the task. Keep it short. Recommended length is 1 to 3 sentences.

.About This Procedure

This paragraph explains or lists special considerations specific to this task. Delete section title and paragraph if not needed.

.Before You Begin

* Bulleted list of pre-requisites that must be in place or done before the user starts this task. 

* Delete section title and bullets if the task has no required pre-requisites.

* Bullet text can be a link to a pre-requisite task that the user must do before starting this task.


.Procedure

_Put steps in a numbered list. The step sequence is important to a repeatable successful outcome._

. Start each step with an active verb, because each step corresponds to one user action.

. Include one command or action per step.

. Format the step line as an unnumbered bullet if the procedure includes only 1 step (exception to numbering the steps).

. Include one command or action per step.

. Include one command or action per step.


.Related Information

* Bulleted list of links to concepts, reference, or other tasks closely related to this task. 

* Include only the most relevant items as links, not every possible related item.

* Delete section title and bullets if no related information is needed.
