[[user_goals_steps]]

= Doing Several Tasks in Sequence

_Start the title with a verb form such as Creating or Create._

_Use this topic template to document a user story or user goal -- any series of tasks that the user must perform in a specific order to accomplish something. The exact sequence of steps is critical to user success._

This paragraph explains what the user will accomplish by following the instructions. It sets context or explains something specific about the goal.

.Prerequisites

This paragraph lists or explains actions the user must perform before starting the procedure. Delete section title and paragraph if not needed.

.Procedure

_Put steps in a numbered list. The step sequence is important to a repeatable successful outcome._

. Link to 1st task to perform.

. Format the step line as an unnumbered bullet if the procedure includes only 1 step (exception to numbering the steps).

. Link to 3rd task to perform.

. Link to the Nth task to perform. 

.Related Information

* Bulleted list of links to concepts, reference, or other tasks closely related to this user story. 

* Include only the most relevant items as links, not every possible related item.

* Delete section title and bullets if no related information is needed.

