[[architecture_overview]]
= Architecture Overview

Installing the  {ProductName} solution involves installing the following components: 

* *Middleware management server*: A JBoss Enterprise Application Platform (EAP) 7 based application that collects metrics and events from middleware servers and sends that data to the CloudForms console. The middleware management server also executes operations on middleware servers.  This is delivered as a Linux container image.
* *PostgreSQL database*: Storage for the middleware inventory. It can be a small scale installation as the quantity of information stored is small and the traffic to the database is low.  This must be separately installed.  RPMs are available for Red Hat Enterprise Linux.
* *Cassandra datastore*: Storage for time series data. Only the middleware manager communicates with the metric store and it is not supported for any other use. This is delivered as a Linux container image.
* *Middleware management agent*: Agents that are installed on the host where the JBoss middleware is running.  Once installed and enabled, the agent can push metrics and events to the middleware management server.  The agent is delivered as a Zip file in the middleware manager container.
