[[installation_prerequisites]]
= Installation Prerequisites

////
What you need before you can install.  Permissions, other components that must
be installed first, etc.
////
The installation instructions for the {ProductName} server assume that you already have the following in place:

* Red Hat Enterprise Linux 7.2 or higher or Red Hat Enterprise Atomic Host 7.2 or higher. For installation instructions, refer to the
link:https://access.redhat.com/documentation/en/red-hat-enterprise-linux/[Red Hat Enterprise Linux installation guide].
* Red Hat CloudForms 4.2 installed.  For installation instructions,  refer to the
link:https://access.redhat.com/documentation/en/red-hat-cloudforms/[Red Hat CloudForms installation guide].
* Docker version 1.8 or higher.
* PostgreSQL 9.4 or higher.


[[docker_configuration]]
== Installing and Configuring Docker

. Register your Linux machine and add the following repositories for Docker support.
+
[source, bash]
----
subscription-manager register --username=<rhnuser> --password=<pwd>
subscription-manager list --available
subscription-manager attach --pool=<pool_id>
subscription-manager repos --enable=rhel-7-server-extras-rpms
----
+
. Install Docker and the required dependencies.
+
[source, bash]
----
yum install docker
----
+
. Start the Docker service.
+
[source, bash]
----
systemctl start docker.service
----
+
. Enable the Docker service.
+
[source, bash]
----
systemctl enable docker.service
----

== Installing and Configuring PostgreSQL Server 9.5
////
Would like to include a short overview of why we need PostgreSQL, that is, what we're using it for vs. Cassandra.
////
Unless you already have a PostgreSQL 9.5 Server installed, you must install it.  You can install PostgreSQL on RHEL systems using `yum`.

. Enable the software collection 2.2 repository to get the required version of PostgreSQL.
+
[source, bash]
----
subscription-manager repos --enable rhel-server-rhscl-7-rpms
----
+
. Install the server.
+
[source, bash]
----
yum install rh-postgresql95
scl enable rh-postgresql95 bash
postgresql-setup --initdb
service rh-postgresql95-postgresql start
systemctl enable rh-postgresql95-postgresql.service
----
+
. Open the firewall for PostgreSQL remote connections.
+
----
sudo firewall-cmd --permanent --add-port=5432/tcp
sudo firewall-cmd --add-port=5432/tcp
----
+
. Edit *_/var/opt/rh/rh-postgresql95/lib/pgsql/data/postgresql.conf_* to allow remote connections.  Add the following line:
+
.postgresql.conf
----
listen_addresses = '*'
----
+
. Edit *_/var/lib/pgsql/data/pg_hba.conf_* to allow a user to connect to the *mwmanager* database.  Add the following line (Replace `_my_db_username_` with the value of your choice):
+
.pg_hba.conf
----
host   mwmanager   my_db_username   0.0.0.0/0   md5
----
+
. Restart PostgreSQL.
+
[source, bash]
----
systemctl restart rh-postgresql95-postgresql.service
----
+
. Create the *mwmanager* database.
+
----
su postgres
systemctl enable rh-postgresql95-postgresql.service
psql
----
+
Replace `_my_db_username_` with the value chosen in *_pg_hba.conf_* and `_my_db_password_` with the value of your choice.
+
----
postgres=# CREATE USER my_db_username WITH PASSWORD 'my_db_password';
postgres=# CREATE DATABASE mwmanager OWNER my_db_username;
----
+
. To verify, connect to the PostgreSQL server remotely.
+
----
psql -h my_db_host -U my_db_username -W -d mwmanager
----
