[[known_issues]]
= Known Issues
////
Consequence - What did the customer experience? What was the symptom? What user action or situation would make this problem manifest?
Cause - Why did this happen?
Workaround (If there is one)- What can you do to avoid or negate the effects of this issue in the meantime?  Sometimes if there is no workaround it is worthwhile telling readers to contact support for advice.
////

NOTE: *Domain mode is not yet fully supported in the technical preview.*

These known issues exist in {ProductName} at this time:

BZ# 
https://bugzilla.redhat.com/show_bug.cgi?id=1387287[1387287]

Hawkular-Services: CVEs found in latest docker image by OpenSCAP scanning tool.

BZ# 
https://bugzilla.redhat.com/show_bug.cgi?id=1387301[1287301]

Cassandra: CVEs found in latest docker image by OpenSCAP scanning tool.

BZ# 
https://bugzilla.redhat.com/show_bug.cgi?id=1390756[1390756]

After deleting an EAP Server Datasource, the deletion event does not appear on the timeline.

BZ#
https://bugzilla.redhat.com/show_bug.cgi?id=1394040[1394040]

When refreshing the status of the middleware manager (Configuration > Refresh Items and Relationships), received the following error: `unknown attribute '_object' for MiddlewareServerGroup`.

BZ# 
https://bugzilla.redhat.com/show_bug.cgi?id=1396225[1396225]

When deploying a WAR file to an EAP domain server running in a container, received an `ERROR: Failed to process` message.

BZ#
https://bugzilla.redhat.com/show_bug.cgi?id=1402126[1392126]

When using an external PostgreSQL for the inventory service, the storage adapter failed to store the available data.

BZ# 
https://bugzilla.redhat.com/show_bug.cgi?id=1403775[1403775]

When starting a second EAP7 domain, the domain mode servers of the first EAP7 domain are missing in the inventory displayed in CloudForms.

BZ# 
https://bugzilla.redhat.com/show_bug.cgi?id=1404270[1404270]

For EAP7 in domain mode, CloudForms does not display the underlying Virtual Machine attribute in the server details.  The underlying VM representation for each EAP7 server in domain mode is also missing in the Topology view.

BZ# 
https://bugzilla.redhat.com/show_bug.cgi?id=1404776[1404776]

Currently there is not a way to enable SSL when starting a Hawkular Services container.

BZ# 
https://bugzilla.redhat.com/show_bug.cgi?id=1405092[1405092]

Middleware manager Server fails to start due to low disk space but does not give a descriptive error message in either the Hawkular Service log or the Cassandra log.

