include::topics/document-attributes.adoc[]

= {Server_Install_BookName}

[[install_chapter_1]]
== Prerequisites
NOTE: This release of {ProductName} is a technical preview. Technology Previews provide early access to upcoming product innovations, letting you to test new features and provide feedback during the development process. Technology Preview releases are _not_ intended for production use.
 For more information see the  https://access.redhat.com/support/offerings/production/scope_moredetail[Red Hat Customer Portal.]

This document provides instructions for installing {ProductName}.  The installation media is two Docker container files available from {ServerDownloadURL}.

include::topics/Architecture_Overview.adoc[leveloffset=+2]

include::topics/Installation_Checklist_Server.adoc[leveloffset=+2]

include::topics/Installation_Prerequisites_Server.adoc[leveloffset=+2]

[[install_chapter_2]]
== Installing the Middleware Management Server

The {ProductName} installation consists of two Docker container images.

IMPORTANT: Do not perform the installation as the ROOT user; create a non-root user.

include::topics/Installing_the_Middleware_Management_Server.adoc[leveloffset=+2]

[[install_chapter_3]]
== Initial Configuration

include::topics/Adding_a_Middleware_Management_Provider.adoc[leveloffset=+2]

include::topics/Installing_the_Middleware_Management_Agent.adoc[leveloffset=+2]

include::topics/Installation_Cassandra_Cluster.adoc[leveloffset=+2]

// **********************************
// * Appendix: Revision Information *
// **********************************
include::topics/revision-info.adoc[]
